// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sommatif2GestionBibliotheque.Models;

#nullable disable

namespace Sommatif2GestionBibliotheque.Migrations
{
    [DbContext(typeof(DbContextBibliotheque))]
    [Migration("20251114030111_AjoutData")]
    partial class AjoutData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auteurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Hugo",
                            Prenom = "Victor"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Zola",
                            Prenom = "Émile"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Dumas",
                            Prenom = "Alexandre"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "La Fontaine",
                            Prenom = "Jean"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Munroe",
                            Prenom = "Myles"
                        });
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Classique"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Fantastique"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Histoire"
                        });
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.DetailsLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId")
                        .IsUnique();

                    b.ToTable("DetailsLivres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISBN = "ISBN-1001",
                            LivreId = 1,
                            NombrePages = 101
                        },
                        new
                        {
                            Id = 2,
                            ISBN = "ISBN-1002",
                            LivreId = 2,
                            NombrePages = 102
                        },
                        new
                        {
                            Id = 3,
                            ISBN = "ISBN-1003",
                            LivreId = 3,
                            NombrePages = 103
                        },
                        new
                        {
                            Id = 4,
                            ISBN = "ISBN-1004",
                            LivreId = 4,
                            NombrePages = 104
                        },
                        new
                        {
                            Id = 5,
                            ISBN = "ISBN-1005",
                            LivreId = 5,
                            NombrePages = 105
                        },
                        new
                        {
                            Id = 6,
                            ISBN = "ISBN-1006",
                            LivreId = 6,
                            NombrePages = 106
                        },
                        new
                        {
                            Id = 7,
                            ISBN = "ISBN-1007",
                            LivreId = 7,
                            NombrePages = 107
                        },
                        new
                        {
                            Id = 8,
                            ISBN = "ISBN-1008",
                            LivreId = 8,
                            NombrePages = 108
                        },
                        new
                        {
                            Id = 9,
                            ISBN = "ISBN-1009",
                            LivreId = 9,
                            NombrePages = 109
                        },
                        new
                        {
                            Id = 10,
                            ISBN = "ISBN-1010",
                            LivreId = 10,
                            NombrePages = 110
                        },
                        new
                        {
                            Id = 11,
                            ISBN = "ISBN-1011",
                            LivreId = 11,
                            NombrePages = 111
                        },
                        new
                        {
                            Id = 12,
                            ISBN = "ISBN-1012",
                            LivreId = 12,
                            NombrePages = 112
                        },
                        new
                        {
                            Id = 13,
                            ISBN = "ISBN-1013",
                            LivreId = 13,
                            NombrePages = 113
                        },
                        new
                        {
                            Id = 14,
                            ISBN = "ISBN-1014",
                            LivreId = 14,
                            NombrePages = 114
                        },
                        new
                        {
                            Id = 15,
                            ISBN = "ISBN-1015",
                            LivreId = 15,
                            NombrePages = 115
                        },
                        new
                        {
                            Id = 16,
                            ISBN = "ISBN-1016",
                            LivreId = 16,
                            NombrePages = 116
                        },
                        new
                        {
                            Id = 17,
                            ISBN = "ISBN-1017",
                            LivreId = 17,
                            NombrePages = 117
                        },
                        new
                        {
                            Id = 18,
                            ISBN = "ISBN-1018",
                            LivreId = 18,
                            NombrePages = 118
                        },
                        new
                        {
                            Id = 19,
                            ISBN = "ISBN-1019",
                            LivreId = 19,
                            NombrePages = 119
                        },
                        new
                        {
                            Id = 20,
                            ISBN = "ISBN-1020",
                            LivreId = 20,
                            NombrePages = 120
                        },
                        new
                        {
                            Id = 21,
                            ISBN = "ISBN-1021",
                            LivreId = 21,
                            NombrePages = 121
                        },
                        new
                        {
                            Id = 22,
                            ISBN = "ISBN-1022",
                            LivreId = 22,
                            NombrePages = 122
                        },
                        new
                        {
                            Id = 23,
                            ISBN = "ISBN-1023",
                            LivreId = 23,
                            NombrePages = 123
                        },
                        new
                        {
                            Id = 24,
                            ISBN = "ISBN-1024",
                            LivreId = 24,
                            NombrePages = 124
                        },
                        new
                        {
                            Id = 25,
                            ISBN = "ISBN-1025",
                            LivreId = 25,
                            NombrePages = 125
                        },
                        new
                        {
                            Id = 26,
                            ISBN = "ISBN-1026",
                            LivreId = 26,
                            NombrePages = 126
                        },
                        new
                        {
                            Id = 27,
                            ISBN = "ISBN-1027",
                            LivreId = 27,
                            NombrePages = 127
                        },
                        new
                        {
                            Id = 28,
                            ISBN = "ISBN-1028",
                            LivreId = 28,
                            NombrePages = 128
                        },
                        new
                        {
                            Id = 29,
                            ISBN = "ISBN-1029",
                            LivreId = 29,
                            NombrePages = 129
                        },
                        new
                        {
                            Id = 30,
                            ISBN = "ISBN-1030",
                            LivreId = 30,
                            NombrePages = 130
                        });
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.ToTable("Livres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuteurId = 3,
                            DatePublication = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 1"
                        },
                        new
                        {
                            Id = 2,
                            AuteurId = 1,
                            DatePublication = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 2"
                        },
                        new
                        {
                            Id = 3,
                            AuteurId = 3,
                            DatePublication = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 3"
                        },
                        new
                        {
                            Id = 4,
                            AuteurId = 5,
                            DatePublication = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 4"
                        },
                        new
                        {
                            Id = 5,
                            AuteurId = 2,
                            DatePublication = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 5"
                        },
                        new
                        {
                            Id = 6,
                            AuteurId = 4,
                            DatePublication = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 6"
                        },
                        new
                        {
                            Id = 7,
                            AuteurId = 1,
                            DatePublication = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 7"
                        },
                        new
                        {
                            Id = 8,
                            AuteurId = 1,
                            DatePublication = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 8"
                        },
                        new
                        {
                            Id = 9,
                            AuteurId = 4,
                            DatePublication = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 9"
                        },
                        new
                        {
                            Id = 10,
                            AuteurId = 2,
                            DatePublication = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 10"
                        },
                        new
                        {
                            Id = 11,
                            AuteurId = 4,
                            DatePublication = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 11"
                        },
                        new
                        {
                            Id = 12,
                            AuteurId = 2,
                            DatePublication = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 12"
                        },
                        new
                        {
                            Id = 13,
                            AuteurId = 5,
                            DatePublication = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 13"
                        },
                        new
                        {
                            Id = 14,
                            AuteurId = 5,
                            DatePublication = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 14"
                        },
                        new
                        {
                            Id = 15,
                            AuteurId = 3,
                            DatePublication = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 15"
                        },
                        new
                        {
                            Id = 16,
                            AuteurId = 3,
                            DatePublication = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 16"
                        },
                        new
                        {
                            Id = 17,
                            AuteurId = 1,
                            DatePublication = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 17"
                        },
                        new
                        {
                            Id = 18,
                            AuteurId = 4,
                            DatePublication = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 18"
                        },
                        new
                        {
                            Id = 19,
                            AuteurId = 2,
                            DatePublication = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 19"
                        },
                        new
                        {
                            Id = 20,
                            AuteurId = 1,
                            DatePublication = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 20"
                        },
                        new
                        {
                            Id = 21,
                            AuteurId = 1,
                            DatePublication = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 21"
                        },
                        new
                        {
                            Id = 22,
                            AuteurId = 5,
                            DatePublication = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 22"
                        },
                        new
                        {
                            Id = 23,
                            AuteurId = 3,
                            DatePublication = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 23"
                        },
                        new
                        {
                            Id = 24,
                            AuteurId = 1,
                            DatePublication = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 24"
                        },
                        new
                        {
                            Id = 25,
                            AuteurId = 4,
                            DatePublication = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 25"
                        },
                        new
                        {
                            Id = 26,
                            AuteurId = 2,
                            DatePublication = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 26"
                        },
                        new
                        {
                            Id = 27,
                            AuteurId = 5,
                            DatePublication = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 27"
                        },
                        new
                        {
                            Id = 28,
                            AuteurId = 4,
                            DatePublication = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 28"
                        },
                        new
                        {
                            Id = 29,
                            AuteurId = 1,
                            DatePublication = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 29"
                        },
                        new
                        {
                            Id = 30,
                            AuteurId = 3,
                            DatePublication = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titre = "Livre Test 30"
                        });
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.LivreCategorie", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("LivreCategories");

                    b.HasData(
                        new
                        {
                            LivreId = 1,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 2,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 3,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 3,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 4,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 4,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 5,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 5,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 6,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 6,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 7,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 7,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 8,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 9,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 9,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 10,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 10,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 11,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 12,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 12,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 13,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 13,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 14,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 14,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 15,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 16,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 16,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 17,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 17,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 18,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 19,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 20,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 20,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 21,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 22,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 22,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 23,
                            CategorieId = 2
                        },
                        new
                        {
                            LivreId = 24,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 24,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 25,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 25,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 26,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 26,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 27,
                            CategorieId = 3
                        },
                        new
                        {
                            LivreId = 27,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 28,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 28,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 29,
                            CategorieId = 4
                        },
                        new
                        {
                            LivreId = 30,
                            CategorieId = 1
                        },
                        new
                        {
                            LivreId = 30,
                            CategorieId = 2
                        });
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.DetailsLivre", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Livre", "Livre")
                        .WithOne("DetailsLivre")
                        .HasForeignKey("Sommatif2GestionBibliotheque.Models.DetailsLivre", "LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.LivreCategorie", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Categorie", "Categorie")
                        .WithMany("LivreCategories")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sommatif2GestionBibliotheque.Models.Livre", "Livre")
                        .WithMany("LivreCategories")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Navigation("LivreCategories");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.Navigation("DetailsLivre")
                        .IsRequired();

                    b.Navigation("LivreCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
