// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sommatif2GestionBibliotheque.Models;

#nullable disable

namespace Sommatif2GestionBibliotheque.Migrations
{
    [DbContext(typeof(DbContextBibliotheque))]
    [Migration("20251113235557_CreateDBandTab")]
    partial class CreateDBandTab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.DetailsLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId")
                        .IsUnique();

                    b.ToTable("DetailsLivres");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.LivreCategorie", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("LivreCategories");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.DetailsLivre", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Livre", "Livre")
                        .WithOne("DetailsLivre")
                        .HasForeignKey("Sommatif2GestionBibliotheque.Models.DetailsLivre", "LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.LivreCategorie", b =>
                {
                    b.HasOne("Sommatif2GestionBibliotheque.Models.Categorie", "Categorie")
                        .WithMany("LivreCategories")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sommatif2GestionBibliotheque.Models.Livre", "Livre")
                        .WithMany("LivreCategories")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Navigation("LivreCategories");
                });

            modelBuilder.Entity("Sommatif2GestionBibliotheque.Models.Livre", b =>
                {
                    b.Navigation("DetailsLivre")
                        .IsRequired();

                    b.Navigation("LivreCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
